### ISSUE TITLE
Redirect other convivio domains to weareconvivio.com

### ISSUE THREAD

**Issue by lewisnyman** [ConvivioTeam/Convivio-Site#46]
A lot of the typo/email domain we bought don't redirect to our site. Here's an email I received from a friend:

> First off, I went to http://convivio.co.uk. I was surprised by what I saw :D
> Then I went to convivio.team, per your e-mail address. That also didn’t quite work!
> Finally I searched for “convivio drupal”, which led me to your d.o company profile page, which led me to http://weareconvivio.com/. That was it. Whew.

**Comment by joesb** [comment]
Moved to ClickUp
