### ISSUE TITLE
Do we still have issues with the cheese wedges on some devices?

### ISSUE THREAD

**Issue by lewisnyman** [ConvivioTeam/Convivio-Site#49]
![screenshot 2017-01-06 11 26 53](https://cloud.githubusercontent.com/assets/632390/21716629/774c7a98-d403-11e6-8011-86e7dbd27fb1.jpg)

**Comment by mikebell** [comment]
I'm seeing it in Chrome dev tools and Chrome on android.
![image](https://cloud.githubusercontent.com/assets/242104/22778401/b6cd3a48-eeae-11e6-9646-e9fde9731e54.png)

**Comment by joesb** [comment]
Moved to ClickUp
