### ISSUE TITLE
Use SSL for the site

### ISSUE THREAD

**Issue by joesb** [ConvivioTeam/Convivio-Site#50]
e.g. with CloudFlare's free Universal SSL
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by joesb** [comment]
What were the problems that you had before when you tried to do this @mikebell @lewisnyman ?

**Comment by lewisnyman** [comment]
@joesb Looks like I had issues with the cookbook: https://weareconvivio.slack.com/archives/infra/p1481037513000035

There isn't a site setup under the cloudflare login. It probably needs to be setup again by someone who knows what they are doing

**Comment by joesb** [comment]
I wonder whether the problem with DNS comes from the main site being on just weareconvivio.com without the www. prefix.

https://cookbook.weareconvivio.com/ is already on SSL – GitBooks uses a cert from Let's Encrypt `Issued by: Let's Encrypt Authority X3` so if DNS for the public site on weareconvivio.com is pushed over to CloudFlare, they handle the DNS with their own name servers and they create an SSL cert for the domain then there'd probably be a load of conflicts. Maybe.

I'll look into what, if anything, can be done at the GitBooks end.
