### ISSUE TITLE
Background image issues in firefox

### ISSUE THREAD

**Issue by lewisnyman** [ConvivioTeam/Convivio-Site#54]
Got a message from a friend:
Hi, Lewis! It may worth to mention to you that the cup on the Convivio frontpage covers the text in FF 54.0 / OSX. (Chrome is OK) 
https://monosnap.com/file/EGU5Qe7qgYIcZ5nYSJsJmNHP2M6ApF#

**Comment by joesb** [comment]
Moved to ClickUp
